notifications:
  email:
    recipients:
      - nicklitwin88@gmail.com
    on_success: change
    on_failure: always
language: node_js
node_js:
  - "0.10"
services: mongodb
branches:
  only:
    - master
before_install:
  # install zeromq
  - echo "yes" | sudo add-apt-repository ppa:chris-lea/libpgm 
  - sudo apt-get update
  - sudo apt-get install libzmq3-dev
  # might not need to make npm directory anymore
  - "mkdir ~/.npm" 
before_script:
  - sleep 15
  - node server.js
